name = "Create Degens"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f4774dd9e805d37fb1543eac44fdc8d8d39d8bfea09f0b9ed074b3917392488"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
