name = "Create Degens"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a743c26f6734565800dd708ce9937a1ed29ebac763d6a2fde6761c1d187f7d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
